### ISSUE TITLE
What are the use cases of this index

### ISSUE THREAD

**Issue by amosbird** [dalibo/hypopg#3]
Hi, according to the `README.md`, I fail to see any use cases of this index. Do you mind adding some examples?

**Comment by rjuju** [comment]
Hello,

I'm not sure I understand your question.  hypopg isn't a new index type, it's just a way to know if postgres would use a given index if it existed before spending too much time/resources to really create it.  This features exists on other RDBMS, usually also name hypothetical indexes or virtual indexes.

I wrote [a blog post](https://rjuju.github.io/postgresql/2015/07/02/how-about-hypothetical-indexes.html) about this extension, is it helpful?

**Comment by amosbird** [comment]
Ah, thanks for the info. Your blog is really helpful :+1:
