### ISSUE TITLE
Index with sort order not being used

### ISSUE THREAD

**Issue by ankane** [dalibo/hypopg#6]
Hey, thanks for this awesome extension!

I think I may have found an issue with using a sort order on Postgres 9.6 (not sure about other versions). Here's code to repro:

```sql
CREATE EXTENSION IF NOT EXISTS hypopg;
SELECT hypopg_reset();

-- create posts
DROP TABLE IF EXISTS posts;
CREATE TABLE posts (
  id int,
  blog_id int,
  user_id int
);
INSERT INTO posts (SELECT n AS id, n % 1000 AS blog_id, n % 10 AS user_id FROM generate_series(1, 100000) n);

-- add hypothetical index and explain
-- i'd expect the hypo index to be used, but it's not
SELECT * FROM hypopg_create_index('CREATE INDEX ON posts (user_id DESC, blog_id)');
EXPLAIN SELECT * FROM posts ORDER BY user_id DESC, blog_id LIMIT 10;

-- add real index and explain
-- the real index is used here, as expected
CREATE INDEX ON posts (user_id DESC, blog_id);
EXPLAIN SELECT * FROM posts ORDER BY user_id DESC, blog_id LIMIT 10;
```

Let me know if anything is unclear.

**Comment by rjuju** [comment]
Hello,

Thanks a lot!  The problem was that the `DESC` entry was computed as `DESC NULLS LAST` while it should have been only `DESC`.

Commit 79220f2c7178faff1161b11241216fd6ed085560 should solve this issue.

**Comment by ankane** [comment]
Awesome, thanks @rjuju for the super quick fix and response. Works great!
